services:
  - type: web
    name: shopai-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 10080
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://shopai-frontend.onrender.com
      - key: UPLOAD_DIR
        value: uploads

  - type: web
    name: shopai-frontend
    runtime: static
    rootDir: frontend
    buildCommand: CI=false npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://shopai-backend-pwk8.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
